// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8ocQDD7WdIRPmCDfsp4QAAaxZCy8Zq0',
    appId: '1:150381460803:web:cd405ecbe8d7090da2c3f6',
    messagingSenderId: '150381460803',
    projectId: 'week8motion',
    authDomain: 'week8motion.firebaseapp.com',
    storageBucket: 'week8motion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFpzwK6fbp3MVHODpr7vft2yCBcuFIuU',
    appId: '1:150381460803:android:bee2f3c9641271cca2c3f6',
    messagingSenderId: '150381460803',
    projectId: 'week8motion',
    storageBucket: 'week8motion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPwfrenBtVXJlB9X7XQrX9CIZbz-euZZ0',
    appId: '1:150381460803:ios:f7ba93e978d6e803a2c3f6',
    messagingSenderId: '150381460803',
    projectId: 'week8motion',
    storageBucket: 'week8motion.firebasestorage.app',
    iosBundleId: 'com.example.assignmentWeek2SlicingUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPwfrenBtVXJlB9X7XQrX9CIZbz-euZZ0',
    appId: '1:150381460803:ios:f7ba93e978d6e803a2c3f6',
    messagingSenderId: '150381460803',
    projectId: 'week8motion',
    storageBucket: 'week8motion.firebasestorage.app',
    iosBundleId: 'com.example.assignmentWeek2SlicingUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8ocQDD7WdIRPmCDfsp4QAAaxZCy8Zq0',
    appId: '1:150381460803:web:54855192cbd8e5d1a2c3f6',
    messagingSenderId: '150381460803',
    projectId: 'week8motion',
    authDomain: 'week8motion.firebaseapp.com',
    storageBucket: 'week8motion.firebasestorage.app',
  );
}
