// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBFk6BFiHPvbtG0pybzFcgBWxBksukko',
    appId: '1:413768131158:web:def138436ff519e48291f7',
    messagingSenderId: '413768131158',
    projectId: 'appnguliks',
    authDomain: 'appnguliks.firebaseapp.com',
    storageBucket: 'appnguliks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc2BUpbZ6X1q5RDzkHlz9PxzmWTRiEGb4',
    appId: '1:413768131158:android:8db91af3492cb88a8291f7',
    messagingSenderId: '413768131158',
    projectId: 'appnguliks',
    storageBucket: 'appnguliks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSaXNs4pIoB0B01GgQZJJ9SjD7BXnjC8Y',
    appId: '1:413768131158:ios:1f347850dd4401598291f7',
    messagingSenderId: '413768131158',
    projectId: 'appnguliks',
    storageBucket: 'appnguliks.firebasestorage.app',
    iosBundleId: 'com.example.tubesNguliks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSaXNs4pIoB0B01GgQZJJ9SjD7BXnjC8Y',
    appId: '1:413768131158:ios:1f347850dd4401598291f7',
    messagingSenderId: '413768131158',
    projectId: 'appnguliks',
    storageBucket: 'appnguliks.firebasestorage.app',
    iosBundleId: 'com.example.tubesNguliks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBFk6BFiHPvbtG0pybzFcgBWxBksukko',
    appId: '1:413768131158:web:f5a476a1a036fa028291f7',
    messagingSenderId: '413768131158',
    projectId: 'appnguliks',
    authDomain: 'appnguliks.firebaseapp.com',
    storageBucket: 'appnguliks.firebasestorage.app',
  );
}
